# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "-l", "140", "--skip-gitignore"]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [--line-length, "140", --skip-magic-trailing-comma]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
#        - --expand-star-imports
#        - --remove-duplicate-keys
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      args:
        [
          "--max-line-length",
          "140",
          "--extend-ignore",
          "E203,F403,F405",
          "--show-source",
        ]
#      additional_dependencies:
#        - flake8-bugbear
#        - flake8-comprehensions
#        - flake8-simplify
